### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by Joalor64** [Joalor64GH/UITest#1]
@yophlox excuse me if you're busy, but could you help me fix a tiny issue with this test app?
the `UIButton` class works normally, but for some reason in `UIWarningSubState`, the buttons won't highlight when hovered over
could you help me fix it plz?

**Comment by st4rxtw** [comment]
I'll try 🙏

**Comment by st4rxtw** [comment]
Update: After messing wit it in school all day, I did NOT find a solution sadly.

**Comment by Joalor64** [comment]
ah
well it's ok
