### ISSUE TITLE
i need help with something else

### ISSUE THREAD

**Issue by Joalor64** [Joalor64GH/UITest#2]
@yophlox for some reason my game started to slow down and i dont know why!!! please help?
https://github.com/Joalor64GH/Rhythmo-SC/

**Comment by st4rxtw** [comment]
wdym by slow down?

**Comment by Joalor64** [comment]
i don't know
in one of the test builds, the game just started being slow

**Comment by Joalor64** [comment]
okay quick update: for some reason, it's only slow on the debug builds???

**Comment by st4rxtw** [comment]
I remember that happening to me when I compiled the UITest, try installing latest haxe and the libraries.

**Comment by Joalor64** [comment]
Hmm okay

**Comment by Joalor64** [comment]
yet another update: since i'm in school rn, i'm testing the game on my school chromebook and the game's only slow on that
so, i can say we're okay now 👍

**Comment by st4rxtw** [comment]
yippee
